export const REGISTER_USERNAME_TAKEN = 'REGISTER_USERNAME_TAKEN';
export const REGISTER_SUCCESSFUL = 'REGISTER_SUCCESSFUL';

export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGIN_UNSUCCESSFUL = 'LOGIN_UNSUCCESSFUL';
export const LOGOUT_USER = 'LOGOUT_USER';

export const GET_USER_EXPENSES = 'GET_USER_EXPENSES';
