// Registration
export const REGISTER_USERNAME_TAKEN = 'REGISTER_USERNAME_TAKEN';
export const REGISTER_SUCCESSFUL = 'REGISTER_SUCCESSFUL';

// User session
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGIN_UNSUCCESSFUL = 'LOGIN_UNSUCCESSFUL';
export const LOGOUT_USER = 'LOGOUT_USER';

// Expenses
export const GET_USER_EXPENSES = 'GET_USER_EXPENSES';
export const GET_USER_CATEGORIES = 'GET_USER_CATEGORIES';
export const ADD_NEW_EXPENSE = 'ADD_NEW_EXPENSE';
export const EDIT_EXPENSE = 'EDIT_EXPENSE';
